import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SessionProviderWrapper from "./provider/SessionProvider";
import RecoilProvider from "./provider/RecoilProvider";
import AppbarClient from "../components/AppbarClient";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <RecoilProvider>
        <SessionProviderWrapper>
          <body className={`${geistSans.variable} ${geistMono.variable}`}>
            <AppbarClient />
            {children}
          </body>
        </SessionProviderWrapper>
      </RecoilProvider>
    </html>
  );
}
